version: '3'
services:
  tomcat-app:
    image: tomcat:latest
    container_name: tomcat-container
    ports:
      - "8082:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/
      - ./src/main/resources/optcg.db:/usr/local/tomcat/optcg.db
    networks:
      - optcg-network
volumes:
  optcg-volume:
networks:
  optcg-network: